-- Esquema del Portal de Atención al Estudiante - UPB
--
-- Se ejecuta con:  uv run inicializar-bd
-- Requiere Oracle 23ai (usa DROP TABLE IF EXISTS y columnas IDENTITY).
--
-- Las sentencias se separan por punto y coma. No incluir bloques PL/SQL en este
-- archivo: el ejecutor los separa por ";" y un bloque BEGIN...END; se partiría mal.

DROP TABLE IF EXISTS seguimientos CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS solicitudes CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS estudiantes CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS funcionarios CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS categorias CASCADE CONSTRAINTS;

CREATE TABLE categorias (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(100)  NOT NULL UNIQUE,
    descripcion  VARCHAR2(500)  NOT NULL,
    sla_horas    NUMBER(5)      NOT NULL
);

CREATE TABLE funcionarios (
    id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR2(150) NOT NULL,
    correo  VARCHAR2(150) NOT NULL UNIQUE,
    area    VARCHAR2(100) NOT NULL,
    activo  NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE estudiantes (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_estudiante  VARCHAR2(20)  NOT NULL UNIQUE,
    nombres            VARCHAR2(100) NOT NULL,
    apellidos          VARCHAR2(100) NOT NULL,
    correo             VARCHAR2(150) NOT NULL UNIQUE,
    carrera            VARCHAR2(120) NOT NULL,
    semestre           NUMBER(2)     NOT NULL,
    activo             NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE solicitudes (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR2(20)   NOT NULL UNIQUE,
    estudiante_id   NUMBER         NOT NULL REFERENCES estudiantes(id),
    categoria_id    NUMBER         NOT NULL REFERENCES categorias(id),
    funcionario_id  NUMBER         REFERENCES funcionarios(id),
    asunto          VARCHAR2(200)  NOT NULL,
    descripcion     VARCHAR2(2000) NOT NULL,
    estado          VARCHAR2(20)   DEFAULT 'RECIBIDA' NOT NULL,
    prioridad       VARCHAR2(10)   DEFAULT 'MEDIA' NOT NULL,
    creada_en       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    actualizada_en  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    cerrada_en      TIMESTAMP,
    CONSTRAINT ck_solicitudes_estado CHECK (
        estado IN ('RECIBIDA', 'EN_REVISION', 'EN_PROCESO', 'RESUELTA', 'CERRADA', 'RECHAZADA')
    ),
    CONSTRAINT ck_solicitudes_prioridad CHECK (
        prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')
    )
);

CREATE TABLE seguimientos (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id  NUMBER         NOT NULL REFERENCES solicitudes(id) ON DELETE CASCADE,
    autor         VARCHAR2(150)  NOT NULL,
    mensaje       VARCHAR2(2000) NOT NULL,
    es_interno    NUMBER(1) DEFAULT 0 NOT NULL,
    creado_en     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX ix_solicitudes_estado ON solicitudes (estado);
CREATE INDEX ix_solicitudes_categoria ON solicitudes (categoria_id);
CREATE INDEX ix_solicitudes_funcionario ON solicitudes (funcionario_id);
CREATE INDEX ix_solicitudes_creada_en ON solicitudes (creada_en);
CREATE INDEX ix_seguimientos_solicitud ON seguimientos (solicitud_id);
